### ISSUE TITLE
Windows Service via NServiceBus.Extensions.Hosting/BackgroundService

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/dotnetTemplates#31]
Is it supported to use NServiceBus.Extension.Hosting/BackgroundService for a windows service endpoint? Is there any special reason that the dotnet templates aren't using these?

Thanks

**Comment by WilliamBZA** [comment]
The templates haven't been updated yet, that's the only reason :)

**Comment by Tobias-Gr** [comment]
OK. Is there a sample/documentation how to use NServiceBusExtensions.Hosting with the default .NET Core 3.1 worker-template? Do I need an own implementation of the BackgroundService-class or does the IHostedService-implementation in UseNServiceBus do the whole job on its own?

Thanks!

**Comment by mauroservienti** [comment]
Hi @Tobias-Gr 

> OK. Is there a sample/documentation how to use NServiceBusExtensions.Hosting with the default .NET Core 3.1 worker-template?

Not yet, we're in the process of upgrading the whole CI infrastructure to enable that. Once the upgrade is done, samples will be made available online.

> Do I need an own implementation of the BackgroundService-class or does the IHostedService-implementation in UseNServiceBus do the whole job on its own?

IIRC, I wasn't involved in the work that created that package, everything is done automatically.

@timbussmann can you confirm?

**Comment by timbussmann** [comment]
`UseNServiceBus` register its own `IHostedService` which will start and stop the endpoint as part of the generic host lifecycle, so there is no need for an additional hosted service (`BackgroundService` is just an implementation of `IHostedService`). Does that help?

**Comment by Tobias-Gr** [comment]
Yes, thanks.
A sample (when ready) would be helpful anyway, especially regarding encapsulation of a common endpoint configuration for all endpoints. I thaught of having a Host base class (based on the one in the old NSB dotnet templates) with a BuildEndpointConfiguration method that I pass as a func to the UseNServiceBus method. But maybe you have other ideas.

**Comment by timbussmann** [comment]
@Tobias-Gr not sure whether I understand you correctly, are you thinking about hosting multiple endpoints in the same generic host?

Creating samples on using the generic host in different scenarios is on our backlog. Currently, the samples are focused on integrating with ASP.NET Core 3 which is the most common use case for the generic host.

**Comment by Tobias-Gr** [comment]
It's not about multiple endpoints in one generic host but about sharing a common endpoint configuration in different endpoints (each in its own generic host).

It's OK for me to wait for the samples.

**Comment by mauroservienti** [comment]
@Tobias-Gr I left a note for the people working on samples to update this issue as well when they are released.

**Comment by danielmarbach** [comment]
@Tobias-Gr There is a PR that shows how the generic host can be leveraged that hopefully will end up being available soon as a sample for downloading

https://github.com/Particular/docs.particular.net/pull/4724

**Comment by danielmarbach** [comment]
The sample is no available at

https://docs.particular.net/samples/hosting/generic-host/

**Comment by Tobias-Gr** [comment]
Thanks!

**Comment by danielmarbach** [comment]
FYI we are also working on updating the templates https://github.com/Particular/dotnetTemplates/pull/43

as a first iteration it will not contain MS logging. We are still working on a good logging integration and would ship that later as an update. But as a first iteration the templates will switch to generic host
