### ISSUE TITLE
Report CI status back to pull requests

### ISSUE THREAD

**Issue by adamralph** [Particular/dotnetTemplates#5]
Currently, not happening. E.g. the build for https://github.com/Particular/dotnetTemplates/pull/4 is failing.

/cc @Particular/host-maintainers @Particular/deployment-maintainers

**Comment by dbelcham** [comment]
@adamralph I just tweaked the github settings for the project. Does #4 look better to you now?

**Comment by adamralph** [comment]
Looks good @dbelcham. Thanks!
